// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParkingApi.Models;

#nullable disable

namespace ParkingApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315224636_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParkingApi.Models.ParkingPlan", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<int?>("HourNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("PeakEndHour")
                        .HasColumnType("integer");

                    b.Property<int?>("PeakStartHour")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Type");

                    b.ToTable("ParkingPlans");
                });

            modelBuilder.Entity("ParkingApi.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ParkingPlansType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParkingSpotNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParkingPlansType");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("ParkingApi.Models.Vehicle", b =>
                {
                    b.Property<string>("LicensePlate")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LicensePlate");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("ParkingApi.Models.Rental", b =>
                {
                    b.HasOne("ParkingApi.Models.ParkingPlan", "ParkingPlan")
                        .WithMany("Rentals")
                        .HasForeignKey("ParkingPlansType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkingApi.Models.Vehicle", "Vehicle")
                        .WithOne("CurrentRental")
                        .HasForeignKey("ParkingApi.Models.Rental", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingPlan");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ParkingApi.Models.ParkingPlan", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("ParkingApi.Models.Vehicle", b =>
                {
                    b.Navigation("CurrentRental");
                });
#pragma warning restore 612, 618
        }
    }
}
