// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parking.Api.Data;

#nullable disable

namespace Parking.Api.Migrations
{
    [DbContext(typeof(ParkingDbContext))]
    [Migration("20260526150630_AddUserLicensePlateVehicleType")]
    partial class AddUserLicensePlateVehicleType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Parking.Api.Entities.ParkingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SpotNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EndTime");

                    b.HasIndex("PlateNumber");

                    b.HasIndex("SpotNumber");

                    b.HasIndex("UserId");

                    b.ToTable("ParkingSessions");
                });

            modelBuilder.Entity("Parking.Api.Entities.ParkingSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EveryNextHourFee")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("FirstHourFee")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("SecondHourFee")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("ParkingSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EveryNextHourFee = 6m,
                            FirstHourFee = 2m,
                            SecondHourFee = 4m
                        });
                });

            modelBuilder.Entity("Parking.Api.Entities.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsForDisabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ParkingSpots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 2,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 3,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 4,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 5,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 6,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 7,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 8,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 9,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 10,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 11,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 12,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 13,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 14,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 15,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 16,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 17,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 18,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 19,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 20,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 21,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 22,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 23,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 24,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 25,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 26,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 27,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 28,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 29,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 30,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 31,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 32,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 33,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 34,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 35,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 36,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 37,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 38,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 39,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 40,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 41,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 42,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 43,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 44,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 45,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 46,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 47,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 48,
                            IsForDisabled = false
                        },
                        new
                        {
                            Id = 49,
                            IsForDisabled = true
                        },
                        new
                        {
                            Id = 50,
                            IsForDisabled = true
                        });
                });

            modelBuilder.Entity("Parking.Api.Entities.UserLicensePlate", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UserId", "PlateNumber");

                    b.HasIndex("UserId");

                    b.ToTable("UserLicensePlates");
                });

            modelBuilder.Entity("Parking.Api.Entities.Vehicle", b =>
                {
                    b.Property<string>("PlateNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("PlateNumber");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Parking.Api.Entities.ParkingSession", b =>
                {
                    b.HasOne("Parking.Api.Entities.Vehicle", "Vehicle")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("PlateNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parking.Api.Entities.ParkingSpot", "ParkingSpot")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("SpotNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingSpot");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Parking.Api.Entities.ParkingSpot", b =>
                {
                    b.Navigation("ParkingSessions");
                });

            modelBuilder.Entity("Parking.Api.Entities.Vehicle", b =>
                {
                    b.Navigation("ParkingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
