// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parking.Api.Data;

#nullable disable

namespace Parking.Api.Migrations
{
    [DbContext(typeof(ParkingDbContext))]
    [Migration("20260414145957_AddParkingSettings")]
    partial class AddParkingSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Parking.Api.Entities.ParkingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SpotNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EndTime");

                    b.HasIndex("PlateNumber");

                    b.HasIndex("SpotNumber");

                    b.HasIndex("UserId");

                    b.ToTable("ParkingSessions");
                });

            modelBuilder.Entity("Parking.Api.Entities.ParkingSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EveryNextHourFee")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("FirstHourFee")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("MaxParkingSpots")
                        .HasColumnType("integer");

                    b.Property<decimal>("SecondHourFee")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("ParkingSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EveryNextHourFee = 6m,
                            FirstHourFee = 2m,
                            MaxParkingSpots = 50,
                            SecondHourFee = 4m
                        });
                });

            modelBuilder.Entity("Parking.Api.Entities.Vehicle", b =>
                {
                    b.Property<string>("PlateNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("PlateNumber");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Parking.Api.Entities.ParkingSession", b =>
                {
                    b.HasOne("Parking.Api.Entities.Vehicle", "Vehicle")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("PlateNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Parking.Api.Entities.Vehicle", b =>
                {
                    b.Navigation("ParkingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
